import { t } from "../../utils/i18n";

export default {
  id: "tutorial_2",
  name: "The corridor",
  map: [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 3, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  ],
  depth: [
    [
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [1, 0],
      [1, 0],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
    ],
    [
      [0, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 1],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [1, 0],
      [0, 0],
    ],
    [
      [0, 0],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
      [0, 1],
    ],
  ],
  audio: "",
  assets: ["", "wall.png", "item.png", "door_close.png"],
  phase: ["conversation", "titleCard", "battle", "conversation", "end"],
  event: [
    {
      position: {},
      item: [],
      scene: [
        {
          background: "",
          people: 1,
          audio: "",
          dialogue: [
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_1"),
              audio: [],
            },
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_2"),
              audio: [],
            },
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_3"),
              audio: [],
            },
          ],
        },
      ],
      trigger: "auto",
    },
    {
      position: { x: 18, y: 2 },
      item: [{ amount: 10, id: "other_currency_1", type: 1 }],
      scene: [
        {
          background: "",
          audio: "",
          people: 1,
          dialogue: [
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_4"),
              audio: [],
            },
            {
              person: "",
              style: "",
              size: "",
              content: "",
              option: [
                {
                  value: t("tutorial_2.option_1.value"),
                  style: "#ffffff",
                  size: "",
                  response: [
                    {
                      person: "",
                      style: "",
                      size: "",
                      content: t("tutorial_2.option_1.response.0"),
                    },
                  ],
                  effect: [],
                },
              ],
            },
            {
              person: "unknow",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_5"),
              audio: [],
            },
          ],
        },
      ],
      trigger: "auto",
    },
    {
      position: { x: 14, y: 2 },
      item: [],
      scene: [
        {
          background: "",
          audio: "",
          people: 1,
          dialogue: [
            {
              person: "unknow",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_6"),
              audio: [],
            },
          ],
        },
      ],
      trigger: "auto",
    },
    {
      position: { x: 2, y: 5 },
      item: [],
      scene: [
        {
          background: "",
          audio: "",
          people: 1,
          dialogue: [
            {
              person: "unknow",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_7"),
              audio: [],
            },
            {
              person: "",
              style: "",
              size: "",
              content: "",
              option: [
                {
                  value: t("tutorial_2.option_2.value"),
                  style: "#ffffff",
                  size: "",
                  response: [
                    {
                      person: "",
                      style: "#ffffff",
                      size: "fontSize_md",
                      content: t("tutorial_2.option_2.response.0"),
                    },
                    {
                      person: "unknow",
                      style: "#FFFFFF",
                      size: "fontSize_md",
                      content: t("tutorial_2.option_2.response.1"),
                    },
                    {
                      person: "unknow",
                      style: "#FFFFFF",
                      size: "fontSize_md",
                      content: t("tutorial_2.option_2.response.2"),
                    },
                    {
                      person: "unknow",
                      style: "#FFFFFF",
                      size: "fontSize_md",
                      content: t("tutorial_2.option_2.response.3"),
                    },
                  ],
                  condition: { type: "item", value: "key", possess: true },
                  effect: [],
                },
                {
                  value: t("tutorial_2.option_3.value"),
                  style: "#ffffff",
                  size: "",
                  response: [
                    {
                      person: "",
                      style: "#ffffff",
                      size: "",
                      content: t("tutorial_2.option_3.response.0"),
                    },
                  ],
                  condition: { type: "", value: "" },
                  effect: [],
                },
              ],
            },
          ],
        },
      ],
      trigger: "once",
    },
    {
      position: { x: 2, y: 7 },
      item: [],
      scene: [
        {
          background: "",
          audio: "",
          people: 1,
          dialogue: [
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_8"),
              audio: [],
            },
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_9"),
              audio: [],
            },
            {
              person: "",
              style: "#ffffff",
              size: "",
              content: "",
              audio: [],
              option: [
                {
                  value: t("tutorial_2.option_4.value"),
                  style: "#ffffff",
                  size: "",
                  response: [
                    {
                      person: "",
                      style: "#FFFFFF",
                      size: "fontSize_md",
                      content: t("tutorial_2.option_4.response.0"),
                    },
                  ],
                  condition: { type: "", value: "" },
                  effect: [],
                },
                {
                  value: t("tutorial_2.option_5.value"),
                  style: "#ffffff",
                  size: "",
                  response: [
                    {
                      person: "",
                      style: "#FFFFFF",
                      size: "fontSize_md",
                      content: t("tutorial_2.option_5.response.0"),
                    },
                    {
                      person: "unknow",
                      style: "#FFFFFF",
                      size: "fontSize_md",
                      content: t("tutorial_2.option_5.response.1"),
                    },
                  ],
                  condition: { type: "", value: "" },
                  effect: [],
                },
              ],
            },
          ],
        },
      ],
      trigger: "option",
      requireOption: "Walk away quietly",
    },
    {
      position: { x: 23, y: 9 },
      item: [],
      scene: [
        {
          background: "",
          audio: "",
          people: 1,
          dialogue: [
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_10"),
              audio: [],
            },
            {
              person: "",
              style: "#FFFFFFD0",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_11"),
              audio: [],
            },
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_12"),
              audio: [],
            },
          ],
        },
      ],
      trigger: "defeat",
      requireOption: "class",
    },
    {
      position: { x: 23, y: 9 },
      item: [],
      scene: [
        {
          background: "",
          audio: "",
          people: 1,
          dialogue: [
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_13"),
              audio: [],
            },
          ],
        },
      ],
      trigger: "option",
      requireOption: "Walk away quietly",
    },
    {
      position: { x: 23, y: 9 },
      item: [],
      scene: [
        {
          background: "",
          audio: "",
          people: 1,
          dialogue: [
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_14"),
              audio: [],
            },
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_15"),
              audio: [],
            },
            {
              person: "",
              style: "#ffffff",
              size: "fontSize_md",
              content: t("tutorial_2.dialogue_16"),
              audio: [],
            },
          ],
        },
      ],
      trigger: "auto",
    },
  ],
  enemy: [
    { startingPoint: { x: 13, y: 1 } },
    { job: "mob_zombie_1", name: "Zombie", startingPoint: { x: 4, y: 2 } },
    { job: "mob_zombie_1", name: "Zombie", startingPoint: { x: 3, y: 1 } },
    { job: "mob_zombie_1", name: "Zombie", startingPoint: { x: 7, y: 7 } },
    { job: "mob_zombie_1", name: "Zombie", startingPoint: { x: 19, y: 6 } },
    { job: "mob_zombie_1", name: "Zombie", startingPoint: { x: 19, y: 7 } },
  ],
  player: [{ startingPoint: { x: 12, y: 1 } }],
  objective: {
    victory: { target: "enemy", value: 0 },
    fail: { target: "player", value: 0 },
    optional: [
      {
        target: "turn",
        value: 6,
        prize: [{ id: "other_currency_1", type: 1, amount: 100 }],
      },
    ],
  },
  difficulty: 1,
};
